[mypy]
python_version = 3.10
check_untyped_defs = False
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True
follow_imports = normal
show_error_codes = True
pretty = True

[mypy-venv.*]
ignore_errors = True

[mypy-wareApp.*]
ignore_errors = True

[mypy-mqtt.tests.*]
ignore_errors = True

# Ignore typing checks for top-level manage script and Celery debug helper
[mypy-manage]
ignore_errors = True

[mypy-warehouse.celery]
ignore_errors = True
