# Generated by Django 3.2.25 on 2026-07-02 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotifications',
            name='actual_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 110968)),
        ),
        migrations.AlterField(
            model_name='alarmnotifications',
            name='off_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 110997)),
        ),
        migrations.AlterField(
            model_name='dailysitereading',
            name='reading_for',
            field=models.DateField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 110494)),
        ),
        migrations.AlterField(
            model_name='meterreadings',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 114834)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 115204)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 19, 12, 54, 115219)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
