# Generated by Django 5.2.16 on 2026-07-29 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wareApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aislegroup",
            name="block_id",
            field=models.ManyToManyField(blank=True, to="wareApp.blockinfo"),
        ),
        migrations.AlterField(
            model_name="aislegroup",
            name="floor",
            field=models.ManyToManyField(blank=True, to="wareApp.floor"),
        ),
        migrations.AlterField(
            model_name="aislegroup",
            name="panel",
            field=models.ManyToManyField(blank=True, to="wareApp.panel"),
        ),
        migrations.AlterField(
            model_name="alarmnotifications",
            name="actual_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="alarmnotifications",
            name="off_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dailysitereading",
            name="reading_for",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="meterreadings",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplyloadtimeshare",
            name="reading_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplyloadtimeshare",
            name="reading_to",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
