"""
Generated by Django 5.2.16 on 2026-07-30 15:56

Flow:
Top-level classes:
- Migration
"""

# Generated by Django 5.2.16 on 2026-07-30 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wareApp", "0002_add_indexes"),
        ("wareApp", "0002_alter_aislegroup_block_id_alter_aislegroup_floor_and_more"),
    ]

    operations = []
