"""
Generated by Django 5.2.16 on 2026-07-30 16:56

Flow:
Top-level classes:
- Migration
"""

# Generated by Django 5.2.16 on 2026-07-30 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wareApp", "0003_backfill_index_fields"),
        ("wareApp", "0003_merge_20260730_1556"),
    ]

    operations = []
