"""
Generated by Django 5.2.16 on 2026-07-30 16:57

Flow:
Top-level classes:
- Migration
"""

# Generated by Django 5.2.16 on 2026-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wareApp", "0004_merge_20260730_1656"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aislegroup",
            name="wa_aisle_site_grp_idx",
        ),
        migrations.AlterField(
            model_name="site",
            name="site_name",
            field=models.CharField(max_length=35),
        ),
        migrations.AddIndex(
            model_name="aislegroup",
            index=models.Index(fields=["site", "aisle_grp_id"], name="wa_aisle_site_grp_idx"),
        ),
    ]
